version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DEBUG=True
      - SECRET_KEY=local-dev-key
      - DATABASE_URL=sqlite:///ctf.db
      - LOG_LEVEL=INFO
      - LOG_FILE=logs/ctf.log
    restart: unless-stopped